# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/colortrack

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/colortrack

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/colortrack/CMakeFiles /home/user/colortrack/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/colortrack/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named colortrack

# Build rule for target.
colortrack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 colortrack
.PHONY : colortrack

# fast build rule for target.
colortrack/fast:
	$(MAKE) -f CMakeFiles/colortrack.dir/build.make CMakeFiles/colortrack.dir/build
.PHONY : colortrack/fast

colortrack.o: colortrack.cpp.o
.PHONY : colortrack.o

# target to build an object file
colortrack.cpp.o:
	$(MAKE) -f CMakeFiles/colortrack.dir/build.make CMakeFiles/colortrack.dir/colortrack.cpp.o
.PHONY : colortrack.cpp.o

colortrack.i: colortrack.cpp.i
.PHONY : colortrack.i

# target to preprocess a source file
colortrack.cpp.i:
	$(MAKE) -f CMakeFiles/colortrack.dir/build.make CMakeFiles/colortrack.dir/colortrack.cpp.i
.PHONY : colortrack.cpp.i

colortrack.s: colortrack.cpp.s
.PHONY : colortrack.s

# target to generate assembly for a file
colortrack.cpp.s:
	$(MAKE) -f CMakeFiles/colortrack.dir/build.make CMakeFiles/colortrack.dir/colortrack.cpp.s
.PHONY : colortrack.cpp.s

comm.o: comm.cpp.o
.PHONY : comm.o

# target to build an object file
comm.cpp.o:
	$(MAKE) -f CMakeFiles/colortrack.dir/build.make CMakeFiles/colortrack.dir/comm.cpp.o
.PHONY : comm.cpp.o

comm.i: comm.cpp.i
.PHONY : comm.i

# target to preprocess a source file
comm.cpp.i:
	$(MAKE) -f CMakeFiles/colortrack.dir/build.make CMakeFiles/colortrack.dir/comm.cpp.i
.PHONY : comm.cpp.i

comm.s: comm.cpp.s
.PHONY : comm.s

# target to generate assembly for a file
comm.cpp.s:
	$(MAKE) -f CMakeFiles/colortrack.dir/build.make CMakeFiles/colortrack.dir/comm.cpp.s
.PHONY : comm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... colortrack"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... colortrack.o"
	@echo "... colortrack.i"
	@echo "... colortrack.s"
	@echo "... comm.o"
	@echo "... comm.i"
	@echo "... comm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

